### ISSUE TITLE
Research Calendar Apps

### ISSUE THREAD

**Issue by Kumar-P05** [Kumar-P05/Calendar#64]
## Description
Research the following productivity apps to determine their features and functionality, and how they compare to the list of features we want to include in our own productivity app:

- [x] Apple Calendar (iOS)
- [x] Apple Calendar (Mac)
- [x] Apple Calendar (web)
- [x] Apple Calendar (iPad)
- [x] Google Calendar (Android)
- [x] Google Calendar (Tablet)
- [x] Google Calendar (web)
- [x] 365 Outlook Calendar (Windows)
- [x] 365 Outlook Calendar (web) 
- [x] 365 Outlook Calendar (Android)
- [x] TickTick
- [x] Cron
- [x] Fantastical
- [x] Daybridge
- [x] Reclaim.ai
- [x] Things 3
- [x] Motion

## Tasks (but not limited to)
- Download and install or use each app on an iOS & Android device and web/windows.
- Test each app's features to see if they match our desired feature list and add new features.
- Take screenshots or make notes of key features and functionalities of each app.
- Document strengths and weaknesses of each app.

**Comment by Kumar-P05** [comment]
Only Mac & iPad left. I'll be going to iTech later today to research there. Wish me luck!

**Comment by Kumar-P05** [comment]
Done.

**Comment by Kumar-P05** [comment]
Done.
